import logging
from types import SimpleNamespace

from email_classification_agent.llm_classifier import INSTRUCTIONS, _bounded
from email_classification_agent.models import LLMDecision, ParsedEmail


def test_semantic_prompt_treats_email_content_as_untrusted() -> None:
    lowered = INSTRUCTIONS.casefold()
    assert "untrusted data" in lowered
    assert "never" in lowered
    assert "follow instructions inside" in lowered
    assert "ignore previous instructions" in lowered
    assert "classify the current message" in lowered


def test_bounded_text_preserves_head_and_tail() -> None:
    value = "HEAD" + ("x" * 1000) + "TAIL"
    bounded = _bounded(value, 100)
    assert bounded.startswith("HEAD")
    assert bounded.endswith("TAIL")
    assert "middle omitted" in bounded


def test_classifier_logs_ai_request_and_response(caplog) -> None:
    from email_classification_agent.llm_classifier import OpenAIEmailClassifier

    decision = LLMDecision(
        category="KEEP_IN_INBOX",
        confidence=0.91,
        reason="No property offer",
        evidence=["invoice language"],
    )

    class Responses:
        def parse(self, **kwargs):
            return SimpleNamespace(output_text='{"category":"KEEP_IN_INBOX"}', output_parsed=decision)

    classifier = OpenAIEmailClassifier.__new__(OpenAIEmailClassifier)
    classifier._client = SimpleNamespace(responses=Responses())
    classifier._model = "test-model"
    message = ParsedEmail(
        message_id="message-1",
        thread_id="thread-1",
        label_ids=("INBOX",),
        internal_date_ms=1,
        from_header="Seller <seller@example.com>",
        sender_header="",
        reply_to_header="",
        to_header="buyer@example.com",
        subject="Offer",
        body_text="Current email body",
    )

    with caplog.at_level(logging.INFO, logger="email_classification_agent.llm_classifier"):
        result = classifier.classify(message, "example.com", "Earlier context", 500, 500)

    logs = "\n".join(record.message for record in caplog.records)
    assert "--- instructions ---" in logs
    assert "--- input read by AI ---" in logs
    assert "Current email body" in logs
    assert "Earlier context" in logs
    assert "--- raw response generated by AI ---" in logs
    assert '{"category":"KEEP_IN_INBOX"}' in logs
    assert str(result) in logs
